services:
  dev:
    build:
      args:
        - DEV_UID=${DEV_UID:-1000}
        - DEV_GID=${DEV_GID:-1000}
      context: .
      dockerfile: docker/Dockerfile
    command:
      - pnpm
      - run
      - dev
    expose:
      - 8000
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ~/.cache/pnpm
        target: /home/node/.cache/pnpm
      - type: bind
        source: ~/.local/share/pnpm/store
        target: /home/node/.local/share/pnpm/store
    working_dir: /app
