version: "3"

silent: true

includes:
  dependencies:
    taskfile: ./taskfiles/dependencies.yaml
    aliases: [d]
  run:
    taskfile: ./taskfiles/run.yaml
    aliases: [r]
  tests:
    taskfile: ./taskfiles/tests.yaml
    aliases: [t]

tasks:
  default:
    cmds:
      - task --list

  down:
    cmds:
      - docker compose down -v --remove-orphans
    desc: Stop and remove all containers

  up:
    cmds:
      - task: dependencies:install
      - task: run:dev
    desc: Start and set up the application
